services:
  app:
    image: ubuntu:22.04
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: local_dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql


volumes:
  postgres_data:
      
      